/* automatically generated by rust-bindgen 0.72.1 */

pub const MOENOTES_VERSION_MAJOR: u32 = 0;
pub const MOENOTES_VERSION_MINOR: u32 = 3;
pub const MOENOTES_VERSION_PATCH: u32 = 0;
pub const MOENOTES_VERSION_STRING: &[u8; 6] = b"0.3.0\0";
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct moenotes_score {
    _unused: [u8; 0],
}
pub type moenotes_score_t = moenotes_score;
pub const moenotes_result_MOENOTES_OK: moenotes_result = 0;
pub const moenotes_result_MOENOTES_ERR_INVALID_ARGUMENT: moenotes_result = 1;
pub const moenotes_result_MOENOTES_ERR_OUT_OF_MEMORY: moenotes_result = 2;
pub const moenotes_result_MOENOTES_ERR_GZIP: moenotes_result = 3;
pub const moenotes_result_MOENOTES_ERR_JSON: moenotes_result = 4;
pub const moenotes_result_MOENOTES_ERR_SCHEMA: moenotes_result = 5;
pub const moenotes_result_MOENOTES_ERR_RANGE: moenotes_result = 6;
pub const moenotes_result_MOENOTES_ERR_INTERNAL: moenotes_result = 7;
pub const moenotes_result_MOENOTES_ERR_UNSUPPORTED: moenotes_result = 8;
pub type moenotes_result = ::std::os::raw::c_uint;
pub use self::moenotes_result as moenotes_result_t;
pub type moenotes_malloc_fn = ::std::option::Option<
    unsafe extern "C" fn(
        ctx: *mut ::std::os::raw::c_void,
        size: usize,
    ) -> *mut ::std::os::raw::c_void,
>;
pub type moenotes_realloc_fn = ::std::option::Option<
    unsafe extern "C" fn(
        ctx: *mut ::std::os::raw::c_void,
        ptr: *mut ::std::os::raw::c_void,
        size: usize,
    ) -> *mut ::std::os::raw::c_void,
>;
pub type moenotes_free_fn = ::std::option::Option<
    unsafe extern "C" fn(ctx: *mut ::std::os::raw::c_void, ptr: *mut ::std::os::raw::c_void),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct moenotes_allocator {
    pub ctx: *mut ::std::os::raw::c_void,
    pub malloc_fn: moenotes_malloc_fn,
    pub realloc_fn: moenotes_realloc_fn,
    pub free_fn: moenotes_free_fn,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
#[cfg(target_pointer_width = "64")]
const _: () = {
    ["Size of moenotes_allocator"][::std::mem::size_of::<moenotes_allocator>() - 32usize];
    ["Alignment of moenotes_allocator"][::std::mem::align_of::<moenotes_allocator>() - 8usize];
    ["Offset of field: moenotes_allocator::ctx"]
        [::std::mem::offset_of!(moenotes_allocator, ctx) - 0usize];
    ["Offset of field: moenotes_allocator::malloc_fn"]
        [::std::mem::offset_of!(moenotes_allocator, malloc_fn) - 8usize];
    ["Offset of field: moenotes_allocator::realloc_fn"]
        [::std::mem::offset_of!(moenotes_allocator, realloc_fn) - 16usize];
    ["Offset of field: moenotes_allocator::free_fn"]
        [::std::mem::offset_of!(moenotes_allocator, free_fn) - 24usize];
};
#[cfg(target_os = "emscripten")]
const _: () = {
    assert!(::std::mem::size_of::<moenotes_allocator>() == 16);
    assert!(::std::mem::align_of::<moenotes_allocator>() == 4);
    assert!(::std::mem::offset_of!(moenotes_allocator, malloc_fn) == 4);
    assert!(::std::mem::offset_of!(moenotes_allocator, realloc_fn) == 8);
    assert!(::std::mem::offset_of!(moenotes_allocator, free_fn) == 12);
};
impl Default for moenotes_allocator {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type moenotes_allocator_t = moenotes_allocator;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct moenotes_parse_options {
    pub start_note_id: i32,
    pub slide_combo_unit: u32,
    pub mirror: u8,
    pub add_flick_hidden: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of moenotes_parse_options"][::std::mem::size_of::<moenotes_parse_options>() - 12usize];
    ["Alignment of moenotes_parse_options"]
        [::std::mem::align_of::<moenotes_parse_options>() - 4usize];
    ["Offset of field: moenotes_parse_options::start_note_id"]
        [::std::mem::offset_of!(moenotes_parse_options, start_note_id) - 0usize];
    ["Offset of field: moenotes_parse_options::slide_combo_unit"]
        [::std::mem::offset_of!(moenotes_parse_options, slide_combo_unit) - 4usize];
    ["Offset of field: moenotes_parse_options::mirror"]
        [::std::mem::offset_of!(moenotes_parse_options, mirror) - 8usize];
    ["Offset of field: moenotes_parse_options::add_flick_hidden"]
        [::std::mem::offset_of!(moenotes_parse_options, add_flick_hidden) - 9usize];
};
pub type moenotes_parse_options_t = moenotes_parse_options;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct moenotes_position {
    pub bar: i32,
    pub rhythm: i32,
    pub rhythmic_unit: i32,
    pub bar_progress: f64,
    pub time_ms: i32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of moenotes_position"][::std::mem::size_of::<moenotes_position>() - 32usize];
    ["Alignment of moenotes_position"][::std::mem::align_of::<moenotes_position>() - 8usize];
    ["Offset of field: moenotes_position::bar"]
        [::std::mem::offset_of!(moenotes_position, bar) - 0usize];
    ["Offset of field: moenotes_position::rhythm"]
        [::std::mem::offset_of!(moenotes_position, rhythm) - 4usize];
    ["Offset of field: moenotes_position::rhythmic_unit"]
        [::std::mem::offset_of!(moenotes_position, rhythmic_unit) - 8usize];
    ["Offset of field: moenotes_position::bar_progress"]
        [::std::mem::offset_of!(moenotes_position, bar_progress) - 16usize];
    ["Offset of field: moenotes_position::time_ms"]
        [::std::mem::offset_of!(moenotes_position, time_ms) - 24usize];
};
pub type moenotes_position_t = moenotes_position;
pub const moenotes_operate_type_MOENOTES_OP_NONE: moenotes_operate_type = 0;
pub const moenotes_operate_type_MOENOTES_OP_NORMAL: moenotes_operate_type = 1;
pub const moenotes_operate_type_MOENOTES_OP_SLIDE_BEGIN: moenotes_operate_type = 20;
pub const moenotes_operate_type_MOENOTES_OP_SLIDE_CONNECTION: moenotes_operate_type = 21;
pub const moenotes_operate_type_MOENOTES_OP_SLIDE_END: moenotes_operate_type = 22;
pub const moenotes_operate_type_MOENOTES_OP_FLICK: moenotes_operate_type = 40;
pub const moenotes_operate_type_MOENOTES_OP_SLIDE_BEGIN_FLICK: moenotes_operate_type = 41;
pub const moenotes_operate_type_MOENOTES_OP_SLIDE_END_FLICK: moenotes_operate_type = 42;
pub const moenotes_operate_type_MOENOTES_OP_TRACE: moenotes_operate_type = 60;
pub const moenotes_operate_type_MOENOTES_OP_SLIDE_BEGIN_TRACE: moenotes_operate_type = 61;
pub const moenotes_operate_type_MOENOTES_OP_SLIDE_END_TRACE: moenotes_operate_type = 62;
pub const moenotes_operate_type_MOENOTES_OP_SLIDE_CONNECTION_TRACE: moenotes_operate_type = 63;
pub const moenotes_operate_type_MOENOTES_OP_HIDDEN_SLIDE_BEGIN: moenotes_operate_type = 80;
pub const moenotes_operate_type_MOENOTES_OP_HIDDEN_SLIDE_END: moenotes_operate_type = 82;
pub const moenotes_operate_type_MOENOTES_OP_GUIDE_BEGIN: moenotes_operate_type = 100;
pub const moenotes_operate_type_MOENOTES_OP_GUIDE_BEGIN_NORMAL: moenotes_operate_type = 101;
pub const moenotes_operate_type_MOENOTES_OP_GUIDE_BEGIN_FLICK: moenotes_operate_type = 102;
pub const moenotes_operate_type_MOENOTES_OP_GUIDE_END: moenotes_operate_type = 103;
pub const moenotes_operate_type_MOENOTES_OP_GUIDE_BEGIN_TRACE: moenotes_operate_type = 104;
pub const moenotes_operate_type_MOENOTES_OP_GUIDE_END_TRACE: moenotes_operate_type = 105;
pub const moenotes_operate_type_MOENOTES_OP_COMBO: moenotes_operate_type = 120;
pub const moenotes_operate_type_MOENOTES_OP_COMBO_SKIP: moenotes_operate_type = 121;
pub const moenotes_operate_type_MOENOTES_OP_HIDDEN: moenotes_operate_type = 122;
pub const moenotes_operate_type_MOENOTES_OP_INVALID_HIDDEN: moenotes_operate_type = 123;
pub type moenotes_operate_type = ::std::os::raw::c_uint;
pub use self::moenotes_operate_type as moenotes_operate_type_t;
pub const moenotes_ease_MOENOTES_EASE_LINEAR: moenotes_ease = 0;
pub const moenotes_ease_MOENOTES_EASE_OUT: moenotes_ease = 1;
pub const moenotes_ease_MOENOTES_EASE_IN: moenotes_ease = 2;
pub type moenotes_ease = ::std::os::raw::c_uint;
pub use self::moenotes_ease as moenotes_ease_t;
pub const moenotes_direction_MOENOTES_DIRECTION_NORMAL: moenotes_direction = 0;
pub const moenotes_direction_MOENOTES_DIRECTION_LEFT: moenotes_direction = 1;
pub const moenotes_direction_MOENOTES_DIRECTION_RIGHT: moenotes_direction = 2;
pub type moenotes_direction = ::std::os::raw::c_uint;
pub use self::moenotes_direction as moenotes_direction_t;
pub const moenotes_alpha_MOENOTES_ALPHA_NONE: moenotes_alpha = 0;
pub const moenotes_alpha_MOENOTES_ALPHA_FADE_IN: moenotes_alpha = 1;
pub const moenotes_alpha_MOENOTES_ALPHA_FADE_OUT: moenotes_alpha = 2;
pub type moenotes_alpha = ::std::os::raw::c_uint;
pub use self::moenotes_alpha as moenotes_alpha_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct moenotes_note_view {
    pub id: i32,
    pub operate_type: moenotes_operate_type_t,
    pub tick: i32,
    pub position: moenotes_position_t,
    pub lane_count: i32,
    pub lane_start: i32,
    pub lane_end: i32,
    pub lane_start_float: f64,
    pub lane_end_float: f64,
    pub width: f64,
    pub critical: u8,
    pub visible: u8,
    pub slide_along: u8,
    pub pos_auto: u8,
    pub pair_note_id: i32,
    pub parent_note_id: i32,
    pub hidden_for_note_id: i32,
    pub line_id: i32,
    pub source_index: i32,
    pub direction: moenotes_direction_t,
    pub ease_left: moenotes_ease_t,
    pub ease_right: moenotes_ease_t,
    pub alpha: moenotes_alpha_t,
    pub line_index: i32,
    pub generated: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of moenotes_note_view"][::std::mem::size_of::<moenotes_note_view>() - 136usize];
    ["Alignment of moenotes_note_view"][::std::mem::align_of::<moenotes_note_view>() - 8usize];
    ["Offset of field: moenotes_note_view::id"]
        [::std::mem::offset_of!(moenotes_note_view, id) - 0usize];
    ["Offset of field: moenotes_note_view::operate_type"]
        [::std::mem::offset_of!(moenotes_note_view, operate_type) - 4usize];
    ["Offset of field: moenotes_note_view::tick"]
        [::std::mem::offset_of!(moenotes_note_view, tick) - 8usize];
    ["Offset of field: moenotes_note_view::position"]
        [::std::mem::offset_of!(moenotes_note_view, position) - 16usize];
    ["Offset of field: moenotes_note_view::lane_count"]
        [::std::mem::offset_of!(moenotes_note_view, lane_count) - 48usize];
    ["Offset of field: moenotes_note_view::lane_start"]
        [::std::mem::offset_of!(moenotes_note_view, lane_start) - 52usize];
    ["Offset of field: moenotes_note_view::lane_end"]
        [::std::mem::offset_of!(moenotes_note_view, lane_end) - 56usize];
    ["Offset of field: moenotes_note_view::lane_start_float"]
        [::std::mem::offset_of!(moenotes_note_view, lane_start_float) - 64usize];
    ["Offset of field: moenotes_note_view::lane_end_float"]
        [::std::mem::offset_of!(moenotes_note_view, lane_end_float) - 72usize];
    ["Offset of field: moenotes_note_view::width"]
        [::std::mem::offset_of!(moenotes_note_view, width) - 80usize];
    ["Offset of field: moenotes_note_view::critical"]
        [::std::mem::offset_of!(moenotes_note_view, critical) - 88usize];
    ["Offset of field: moenotes_note_view::visible"]
        [::std::mem::offset_of!(moenotes_note_view, visible) - 89usize];
    ["Offset of field: moenotes_note_view::slide_along"]
        [::std::mem::offset_of!(moenotes_note_view, slide_along) - 90usize];
    ["Offset of field: moenotes_note_view::pos_auto"]
        [::std::mem::offset_of!(moenotes_note_view, pos_auto) - 91usize];
    ["Offset of field: moenotes_note_view::pair_note_id"]
        [::std::mem::offset_of!(moenotes_note_view, pair_note_id) - 92usize];
    ["Offset of field: moenotes_note_view::parent_note_id"]
        [::std::mem::offset_of!(moenotes_note_view, parent_note_id) - 96usize];
    ["Offset of field: moenotes_note_view::hidden_for_note_id"]
        [::std::mem::offset_of!(moenotes_note_view, hidden_for_note_id) - 100usize];
    ["Offset of field: moenotes_note_view::line_id"]
        [::std::mem::offset_of!(moenotes_note_view, line_id) - 104usize];
    ["Offset of field: moenotes_note_view::source_index"]
        [::std::mem::offset_of!(moenotes_note_view, source_index) - 108usize];
    ["Offset of field: moenotes_note_view::direction"]
        [::std::mem::offset_of!(moenotes_note_view, direction) - 112usize];
    ["Offset of field: moenotes_note_view::ease_left"]
        [::std::mem::offset_of!(moenotes_note_view, ease_left) - 116usize];
    ["Offset of field: moenotes_note_view::ease_right"]
        [::std::mem::offset_of!(moenotes_note_view, ease_right) - 120usize];
    ["Offset of field: moenotes_note_view::alpha"]
        [::std::mem::offset_of!(moenotes_note_view, alpha) - 124usize];
    ["Offset of field: moenotes_note_view::line_index"]
        [::std::mem::offset_of!(moenotes_note_view, line_index) - 128usize];
    ["Offset of field: moenotes_note_view::generated"]
        [::std::mem::offset_of!(moenotes_note_view, generated) - 132usize];
};
impl Default for moenotes_note_view {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type moenotes_note_view_t = moenotes_note_view;
pub const moenotes_event_type_MOENOTES_EVENT_SKILL: moenotes_event_type = 0;
pub const moenotes_event_type_MOENOTES_EVENT_FEVER: moenotes_event_type = 1;
pub const moenotes_event_type_MOENOTES_EVENT_CALL: moenotes_event_type = 2;
pub type moenotes_event_type = ::std::os::raw::c_uint;
pub use self::moenotes_event_type as moenotes_event_type_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct moenotes_event {
    pub type_: moenotes_event_type_t,
    pub tick: i32,
    pub end_tick: i32,
    pub position: moenotes_position_t,
    pub end_position: moenotes_position_t,
    pub value_count: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of moenotes_event"][::std::mem::size_of::<moenotes_event>() - 88usize];
    ["Alignment of moenotes_event"][::std::mem::align_of::<moenotes_event>() - 8usize];
    ["Offset of field: moenotes_event::type_"]
        [::std::mem::offset_of!(moenotes_event, type_) - 0usize];
    ["Offset of field: moenotes_event::tick"]
        [::std::mem::offset_of!(moenotes_event, tick) - 4usize];
    ["Offset of field: moenotes_event::end_tick"]
        [::std::mem::offset_of!(moenotes_event, end_tick) - 8usize];
    ["Offset of field: moenotes_event::position"]
        [::std::mem::offset_of!(moenotes_event, position) - 16usize];
    ["Offset of field: moenotes_event::end_position"]
        [::std::mem::offset_of!(moenotes_event, end_position) - 48usize];
    ["Offset of field: moenotes_event::value_count"]
        [::std::mem::offset_of!(moenotes_event, value_count) - 80usize];
};
impl Default for moenotes_event {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type moenotes_event_t = moenotes_event;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct moenotes_line_sample {
    pub lane_start: f64,
    pub lane_end: f64,
    pub width: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of moenotes_line_sample"][::std::mem::size_of::<moenotes_line_sample>() - 24usize];
    ["Alignment of moenotes_line_sample"][::std::mem::align_of::<moenotes_line_sample>() - 8usize];
    ["Offset of field: moenotes_line_sample::lane_start"]
        [::std::mem::offset_of!(moenotes_line_sample, lane_start) - 0usize];
    ["Offset of field: moenotes_line_sample::lane_end"]
        [::std::mem::offset_of!(moenotes_line_sample, lane_end) - 8usize];
    ["Offset of field: moenotes_line_sample::width"]
        [::std::mem::offset_of!(moenotes_line_sample, width) - 16usize];
};
pub type moenotes_line_sample_t = moenotes_line_sample;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct moenotes_line_view {
    pub id: i32,
    pub line_index: i32,
    pub source_index: i32,
    pub begin_note_id: i32,
    pub end_note_id: i32,
    pub guide: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of moenotes_line_view"][::std::mem::size_of::<moenotes_line_view>() - 24usize];
    ["Alignment of moenotes_line_view"][::std::mem::align_of::<moenotes_line_view>() - 4usize];
    ["Offset of field: moenotes_line_view::id"]
        [::std::mem::offset_of!(moenotes_line_view, id) - 0usize];
    ["Offset of field: moenotes_line_view::line_index"]
        [::std::mem::offset_of!(moenotes_line_view, line_index) - 4usize];
    ["Offset of field: moenotes_line_view::source_index"]
        [::std::mem::offset_of!(moenotes_line_view, source_index) - 8usize];
    ["Offset of field: moenotes_line_view::begin_note_id"]
        [::std::mem::offset_of!(moenotes_line_view, begin_note_id) - 12usize];
    ["Offset of field: moenotes_line_view::end_note_id"]
        [::std::mem::offset_of!(moenotes_line_view, end_note_id) - 16usize];
    ["Offset of field: moenotes_line_view::guide"]
        [::std::mem::offset_of!(moenotes_line_view, guide) - 20usize];
};
pub type moenotes_line_view_t = moenotes_line_view;
pub const moenotes_warning_MOENOTES_WARNING_NONE: moenotes_warning = 0;
pub const moenotes_warning_MOENOTES_WARNING_NONMONOTONIC_LINE: moenotes_warning = 1;
pub const moenotes_warning_MOENOTES_WARNING_SHARED_ENDPOINT: moenotes_warning = 2;
pub type moenotes_warning = ::std::os::raw::c_uint;
pub use self::moenotes_warning as moenotes_warning_t;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct moenotes_bpm_event {
    pub tick: i32,
    pub bpm: f64,
    pub position: moenotes_position_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of moenotes_bpm_event"][::std::mem::size_of::<moenotes_bpm_event>() - 48usize];
    ["Alignment of moenotes_bpm_event"][::std::mem::align_of::<moenotes_bpm_event>() - 8usize];
    ["Offset of field: moenotes_bpm_event::tick"]
        [::std::mem::offset_of!(moenotes_bpm_event, tick) - 0usize];
    ["Offset of field: moenotes_bpm_event::bpm"]
        [::std::mem::offset_of!(moenotes_bpm_event, bpm) - 8usize];
    ["Offset of field: moenotes_bpm_event::position"]
        [::std::mem::offset_of!(moenotes_bpm_event, position) - 16usize];
};
pub type moenotes_bpm_event_t = moenotes_bpm_event;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct moenotes_signature_event {
    pub tick: i32,
    pub numerator: i32,
    pub denominator: i32,
    pub position: moenotes_position_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of moenotes_signature_event"]
        [::std::mem::size_of::<moenotes_signature_event>() - 48usize];
    ["Alignment of moenotes_signature_event"]
        [::std::mem::align_of::<moenotes_signature_event>() - 8usize];
    ["Offset of field: moenotes_signature_event::tick"]
        [::std::mem::offset_of!(moenotes_signature_event, tick) - 0usize];
    ["Offset of field: moenotes_signature_event::numerator"]
        [::std::mem::offset_of!(moenotes_signature_event, numerator) - 4usize];
    ["Offset of field: moenotes_signature_event::denominator"]
        [::std::mem::offset_of!(moenotes_signature_event, denominator) - 8usize];
    ["Offset of field: moenotes_signature_event::position"]
        [::std::mem::offset_of!(moenotes_signature_event, position) - 16usize];
};
pub type moenotes_signature_event_t = moenotes_signature_event;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct moenotes_command {
    pub time_ms: i32,
    pub current_combo: i32,
    pub current_life: i32,
    pub note_id: i32,
    pub operate_type: moenotes_operate_type_t,
    pub score_type: i32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of moenotes_command"][::std::mem::size_of::<moenotes_command>() - 24usize];
    ["Alignment of moenotes_command"][::std::mem::align_of::<moenotes_command>() - 4usize];
    ["Offset of field: moenotes_command::time_ms"]
        [::std::mem::offset_of!(moenotes_command, time_ms) - 0usize];
    ["Offset of field: moenotes_command::current_combo"]
        [::std::mem::offset_of!(moenotes_command, current_combo) - 4usize];
    ["Offset of field: moenotes_command::current_life"]
        [::std::mem::offset_of!(moenotes_command, current_life) - 8usize];
    ["Offset of field: moenotes_command::note_id"]
        [::std::mem::offset_of!(moenotes_command, note_id) - 12usize];
    ["Offset of field: moenotes_command::operate_type"]
        [::std::mem::offset_of!(moenotes_command, operate_type) - 16usize];
    ["Offset of field: moenotes_command::score_type"]
        [::std::mem::offset_of!(moenotes_command, score_type) - 20usize];
};
impl Default for moenotes_command {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type moenotes_command_t = moenotes_command;
unsafe extern "C" {
    pub fn moenotes_version_string() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn moenotes_default_parse_options(options: *mut moenotes_parse_options_t);
}
unsafe extern "C" {
    pub fn moenotes_result_string(result: moenotes_result_t) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn moenotes_operate_type_name(
        type_: moenotes_operate_type_t,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn moenotes_operate_type_is_judgement(type_: moenotes_operate_type_t) -> u8;
}
unsafe extern "C" {
    pub fn moenotes_score_parse(
        data: *const ::std::os::raw::c_void,
        size: usize,
        options: *const moenotes_parse_options_t,
        allocator: *const moenotes_allocator_t,
        out_score: *mut *mut moenotes_score_t,
        error_message: *mut ::std::os::raw::c_char,
        error_message_size: usize,
    ) -> moenotes_result_t;
}
unsafe extern "C" {
    pub fn moenotes_score_free(score: *mut moenotes_score_t);
}
unsafe extern "C" {
    pub fn moenotes_score_note_count(score: *const moenotes_score_t) -> usize;
}
unsafe extern "C" {
    pub fn moenotes_score_note_at(
        score: *const moenotes_score_t,
        index: usize,
        out_note: *mut moenotes_note_view_t,
    ) -> moenotes_result_t;
}
unsafe extern "C" {
    pub fn moenotes_score_source_note_at(
        score: *const moenotes_score_t,
        index: usize,
        out_note: *mut moenotes_note_view_t,
    ) -> moenotes_result_t;
}
unsafe extern "C" {
    pub fn moenotes_score_lane_count(score: *const moenotes_score_t) -> i32;
}
unsafe extern "C" {
    pub fn moenotes_score_warnings(score: *const moenotes_score_t) -> u32;
}
unsafe extern "C" {
    pub fn moenotes_score_bpm_count(score: *const moenotes_score_t) -> usize;
}
unsafe extern "C" {
    pub fn moenotes_score_bpm_at(
        score: *const moenotes_score_t,
        index: usize,
        out_event: *mut moenotes_bpm_event_t,
    ) -> moenotes_result_t;
}
unsafe extern "C" {
    pub fn moenotes_score_signature_count(score: *const moenotes_score_t) -> usize;
}
unsafe extern "C" {
    pub fn moenotes_score_signature_at(
        score: *const moenotes_score_t,
        index: usize,
        out_event: *mut moenotes_signature_event_t,
    ) -> moenotes_result_t;
}
unsafe extern "C" {
    pub fn moenotes_score_position_at_tick(
        score: *const moenotes_score_t,
        tick: i32,
        out_position: *mut moenotes_position_t,
    ) -> moenotes_result_t;
}
unsafe extern "C" {
    pub fn moenotes_score_note_position_at_tick(
        score: *const moenotes_score_t,
        tick: i32,
        out_position: *mut moenotes_position_t,
    ) -> moenotes_result_t;
}
unsafe extern "C" {
    pub fn moenotes_score_event_count(score: *const moenotes_score_t) -> usize;
}
unsafe extern "C" {
    pub fn moenotes_score_event_at(
        score: *const moenotes_score_t,
        index: usize,
        out_event: *mut moenotes_event_t,
    ) -> moenotes_result_t;
}
unsafe extern "C" {
    pub fn moenotes_score_event_value_at(
        score: *const moenotes_score_t,
        event_index: usize,
        value_index: usize,
        out_value: *mut i32,
    ) -> moenotes_result_t;
}
unsafe extern "C" {
    pub fn moenotes_score_call_rhythm_count(
        score: *const moenotes_score_t,
        event_index: usize,
    ) -> usize;
}
unsafe extern "C" {
    pub fn moenotes_score_call_rhythm_at(
        score: *const moenotes_score_t,
        event_index: usize,
        rhythm_index: usize,
        out_progress: *mut f64,
    ) -> moenotes_result_t;
}
unsafe extern "C" {
    pub fn moenotes_score_bar_line_count(score: *const moenotes_score_t) -> usize;
}
unsafe extern "C" {
    pub fn moenotes_score_bar_line_at(
        score: *const moenotes_score_t,
        index: usize,
        out_position: *mut moenotes_position_t,
    ) -> moenotes_result_t;
}
unsafe extern "C" {
    pub fn moenotes_score_last_timing_note_count(score: *const moenotes_score_t) -> usize;
}
unsafe extern "C" {
    pub fn moenotes_score_last_timing_note_at(
        score: *const moenotes_score_t,
        index: usize,
        out_note: *mut moenotes_note_view_t,
    ) -> moenotes_result_t;
}
unsafe extern "C" {
    pub fn moenotes_score_note_fever_event(
        score: *const moenotes_score_t,
        note_id: i32,
        out_event_index: *mut i32,
    ) -> moenotes_result_t;
}
unsafe extern "C" {
    pub fn moenotes_score_line_count(score: *const moenotes_score_t) -> usize;
}
unsafe extern "C" {
    pub fn moenotes_score_line_at(
        score: *const moenotes_score_t,
        index: usize,
        out_line: *mut moenotes_line_view_t,
    ) -> moenotes_result_t;
}
unsafe extern "C" {
    pub fn moenotes_score_note_line_count(score: *const moenotes_score_t, note_id: i32) -> usize;
}
unsafe extern "C" {
    pub fn moenotes_score_note_line_at(
        score: *const moenotes_score_t,
        note_id: i32,
        index: usize,
        out_line_id: *mut i32,
    ) -> moenotes_result_t;
}
unsafe extern "C" {
    pub fn moenotes_score_sample_line(
        score: *const moenotes_score_t,
        line_id: i32,
        tick: i32,
        out_sample: *mut moenotes_line_sample_t,
    ) -> moenotes_result_t;
}
unsafe extern "C" {
    pub fn moenotes_score_sample_judgement_line(
        score: *const moenotes_score_t,
        line_id: i32,
        tick: i32,
        out_sample: *mut moenotes_line_sample_t,
    ) -> moenotes_result_t;
}
unsafe extern "C" {
    pub fn moenotes_score_line_member_count(score: *const moenotes_score_t, line_id: i32) -> usize;
}
unsafe extern "C" {
    pub fn moenotes_score_line_member_at(
        score: *const moenotes_score_t,
        line_id: i32,
        index: usize,
        out_note: *mut moenotes_note_view_t,
    ) -> moenotes_result_t;
}
unsafe extern "C" {
    pub fn moenotes_score_full_combo_count(
        score: *const moenotes_score_t,
        include_slide_combos: u8,
        include_hidden_flick_nodes: u8,
    ) -> u32;
}
unsafe extern "C" {
    pub fn moenotes_score_command_count(score: *const moenotes_score_t) -> usize;
}
unsafe extern "C" {
    pub fn moenotes_score_command_at(
        score: *const moenotes_score_t,
        index: usize,
        score_type: i32,
        current_life: i32,
        current_combo: i32,
        out_command: *mut moenotes_command_t,
    ) -> moenotes_result_t;
}
